### ISSUE TITLE
update PicoGW_UI or how to compile for windows

### ISSUE THREAD

**Issue by nestorayuso** [Lora-net/picoGW_hal#5]
The latest version of PicoGW_UI located at https://www.semtech.com/uploads/documents/PicoGW_UI_Release_V1.0.3.2.zip uses the outdated version 0.2.0 of HAL library.

It would be fine to release an updated version of PicoGW_UI or the steps to compile this project for windows.

**Comment by x893** [comment]
Also very helpfull if you can add sources for PicoGW_UI and other exe files.

**Comment by x893** [comment]
No information ?

**Comment by nestorayuso** [comment]
seems like Semtech updated the version for PicoGW_UI
https://www.semtech.com/uploads/documents/PicoGW_UI_Release_V1.0.3.4.zip
but still uses the outdated version 0.2.0 of HAL library.

**Comment by x893** [comment]
Looks interesting but more interesting sources for PacketForwarder.exe

**Comment by x893** [comment]
I think about this device. Looks good and not expensive
https://www.n-fuse.co/devices/LoRaWAN-Concentrator-Card-mini-PCIe.html

**Comment by foster0905** [comment]
Does anyone know how to update the latest version of picoGW_hal for PicoGW?
Current version of picoGW_hal is still 0.2.0 in PicoGW_UI.zip/pgw.dfu.

I have the problem. The PicoGW often show following error message:

ERROR: [down] Packet REJECTED (jit error=2 Too early to queue this packet)

I not sure this error is relative to picoGW_hal was outdated, but I want to try the latest version.
